BitgetOrdersStateMachine:
  Type: AWS::StepFunctions::StateMachine
  Properties:
    StateMachineName: BitgetOrdersStateMachine
    DefinitionString:
      Fn::Sub: |
        {
          "Comment": "Bitget Orders Extraction - Optimized Parallel",
          "StartAt": "ProcessSymbols",
          "States": {
            "ProcessSymbols": {
              "Type": "Map",
              "ItemsPath": "$.symbols",
              "MaxConcurrency": 50,          # Ajusta según la capacidad de tus Lambdas
              "Iterator": {
                "StartAt": "ExtractOrders",
                "States": {
                  "ExtractOrders": {
                    "Type": "Task",
                    "Resource": "${WorkerFunction.Arn}",
                    "Parameters": {
                      "symbol.$": "$"
                    },
                    "End": true
                  }
                }
              },
              "ResultPath": "$.results",
              "Next": "CollectResults"
            },
            "CollectResults": {
              "Type": "Task",
              "Resource": "${CollectorFunction.Arn}",
              "End": true
            }
          }
        }
    RoleArn:
      Fn::GetAtt:
        - StepFunctionRole
        - Arn
